### ISSUE TITLE
AKAZE compilation error

### ISSUE THREAD

**Issue by geekyta** [sweeneychris/TheiaSfM#123]
I want to build Theia and I get this error. Couldn't figure out the reason.

CMakeFiles/akaze_match.dir/akaze_match.cpp.o: In function `cimg_library::cimg::mutex(unsigned int, int)':
akaze_match.cpp:(.text._ZN12cimg_library4cimg5mutexEji[_ZN12cimg_library4cimg5mutexEji]+0x53): undefined reference to `pthread_mutex_trylock'
collect2: error: ld returned 1 exit status
libraries/akaze/CMakeFiles/akaze_match.dir/build.make:95: recipe for target 'libraries/akaze/bin/akaze_match' failed
make[2]: *** [libraries/akaze/bin/akaze_match] Error 1
CMakeFiles/Makefile2:333: recipe for target 'libraries/akaze/CMakeFiles/akaze_match.dir/all' failed
make[1]: *** [libraries/akaze/CMakeFiles/akaze_match.dir/all] Error 2

**Comment by sweeneychris** [comment]
Are you synced to the master branch? I believe this issue was resolved

**Comment by geekyta** [comment]
Yes, I cloned the master branch today, and have been trying to build it.

**Comment by sweeneychris** [comment]
What OS and compiler are you using?

**Comment by geekyta** [comment]
The OS is: Ubuntu 16.04.1 LTS
And the compiler is: gcc version 5.4.0

**Comment by QifanHe** [comment]
I got the same error on both Ubuntu 16.04.1 LTS and 14.04 LTS:
`[ 12%] Building CXX object src/theia/CMakeFiles/theia.dir/io/read_matches.cc.o
Linking CXX executable bin/akaze_match
CMakeFiles/akaze_match.dir/akaze_match.cpp.o: In function `cimg_library::cimg::mutex(unsigned int, int)':
akaze_match.cpp:(.text._ZN12cimg_library4cimg5mutexEji[_ZN12cimg_library4cimg5mutexEji]+0x53): undefined reference to `pthread_mutex_trylock'
collect2: error: ld returned 1 exit status
make[2]: *** [libraries/akaze/bin/akaze_match] Error 1
make[1]: *** [libraries/akaze/CMakeFiles/akaze_match.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
`

**Comment by QifanHe** [comment]
I just found a way to solve it. Downgrade your gcc version to a previous one(mine from 5.4.1 -> 4.8.5). Then it would work for you. Good luck!
I done this by:
`sudo apt-get remove gcc g++`
`sudo apt-get install build-essential`

**Comment by geekyta** [comment]
Great. Thanks so much, @QifanHe . I did the same and that problem got resolved. However, I'm getting new error which I couldn't fix that yet too. Here is the error I get: 
../../lib/libtheia.a(image.cc.o): In function `theia::FloatImage::Resize(int, int)':
image.cc:(.text+0x2162): undefined reference to `OpenImageIO::v1_8::geterror()'
collect2: error: ld returned 1 exit status
src/theia/CMakeFiles/image_test.dir/build.make:167: recipe for target 'bin/image_test' failed
make[2]: *** [bin/image_test] Error 1
CMakeFiles/Makefile2:1186: recipe for target 'src/theia/CMakeFiles/image_test.dir/all' failed
make[1]: *** [src/theia/CMakeFiles/image_test.dir/all] Error 2
Makefile:160: recipe for target 'all' failed

**Comment by sweeneychris** [comment]
Please use OpenImageIO 1.6 and that should fix it.

**Comment by geekyta** [comment]
I used OpeImageIO 1.6 and I still have issues:

../../lib/libtheia.a(image.cc.o): In function `theia::FloatImage::Resize(int, int)':
image.cc:(.text+0x2162): undefined reference to `OpenImageIO::v1_6::geterror()'
/usr/local/lib/libOpenImageIO.so: undefined reference to `Imf_2_2::TypedAttribute<std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::staticTypeName()'
/usr/local/lib/libOpenImageIO.so: undefined reference to `Imf_2_2::TypedAttribute<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::writeValueTo(Imf_2_2::OStream&, int) const'
/usr/local/lib/libOpenImageIO.so: undefined reference to `Imf_2_2::TypedAttribute<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::readValueFrom(Imf_2_2::IStream&, int, int)'
/usr/local/lib/libOpenImageIO.so: undefined reference to `Imf_2_2::Header::type[abi:cxx11]() const'
/usr/local/lib/libOpenImageIO.so: undefined reference to `Imf_2_2::TypedAttribute<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::staticTypeName()'
/usr/local/lib/libOpenImageIO.so: undefined reference to `Imf_2_2::Header::setType(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/local/lib/libOpenImageIO.so: undefined reference to `Imf_2_2::TypedAttribute<std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::readValueFrom(Imf_2_2::IStream&, int, int)'
/usr/local/lib/libOpenImageIO.so: undefined reference to `Imf_2_2::TypedAttribute<std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::writeValueTo(Imf_2_2::OStream&, int) const'
/usr/local/lib/libOpenImageIO.so: undefined reference to `Imf_2_2::Header::name[abi:cxx11]() const'
collect2: error: ld returned 1 exit status

I thought it might be because the compiler has changed (downgraded to gcc 4.8) and that is causing issues, but I rebuilt every prerequisite package for openImageIO with gcc 4.8, but that did not resolve that either.

**Comment by LostXine** [comment]
That means you should link "pthead" when compiling.
Try this:

- Edit 'TheiaSFM/libraries/akaze/CmakeList.txt'
- Replace 'TARGET_LINK_LIBRARIES(akaze_match akaze ${CIMG_LIBRARIES})' (LINE 108) with 
 'TARGET_LINK_LIBRARIES(akaze_match akaze ${CIMG_LIBRARIES} pthead)'
- Save and quit.

Good luck.

**Comment by JunhyeopLee** [comment]
in my case, I used bash command prompt on windows 10 pro. and it works without any changing cmake list file or the other things.
However, when using power shell prompt, it doesn't work as showing the 'pthread' issues.

**Comment by sweeneychris** [comment]
this should be fixed in the master branch now. please feel free to reopen this issue if you're still having problems.
